# Generated by Django 3.2 on 2022-02-20 01:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('postpones', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('choice1', 'Low'), ('choice2', 'Medium'), ('choice3', 'Hard')], max_length=10)),
                ('restored', models.BooleanField(default=False)),
                ('first_created', models.DateField(default=datetime.date(1998, 12, 25))),
                ('old_id', models.IntegerField(default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDo.category')),
            ],
        ),
        migrations.CreateModel(
            name='RecycleBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('postpones', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('priority', models.CharField(max_length=10)),
                ('idd', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDo.category')),
            ],
        ),
    ]
