# Generated by Django 3.2 on 2022-02-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='test', max_length=50, primary_key=True, serialize=False),
        ),
    ]
